version: "{build}"

clone_depth: 1

environment:
  nodejs_version: "6"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - mkdir hosts
  - mkdir spidermonkey
  - curl -fsS -o spidermonkey\jsshell-win64.zip https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/jsshell-win64.zip
  - 7z e -o%CD%\spidermonkey spidermonkey\jsshell-win64.zip
  - set PATH=%PATH%;%CD%\spidermonkey\
  - where js
  - mkdir chakracore
  - curl -fsSL -o chakracore\cc_windows_all_1_7_1.zip https://aka.ms/chakracore/cc_windows_all_1_7_1
  - 7z -y e -o%CD%\chakracore chakracore\cc_windows_all_1_7_1.zip
  - set PATH=%PATH%;%CD%\chakracore\
  - where ch
  - echo %PATH%
  - node -v
  - npm install

build: off

test_script:
  - cmd: npm test

matrix:
  fast_finish: true
