#!/bin/sh

if [ -z $(which esvu) ]; then
  npm install --ignore-scripts;
  npm install esvu -g;
  esvu --engines=all;
fi;

export ESHOST_ESVU_PATH="${HOME}/.esvu/bin";
export PATH="${ESHOST_ESVU_PATH}:${PATH}";

ESHOST_CHAKRA_PATH=$ESHOST_ESVU_PATH/chakra;
ESHOST_ENGINE262_PATH=$ESHOST_ESVU_PATH/engine262;
ESHOST_JSC_PATH=$ESHOST_ESVU_PATH/jsc;
ESHOST_JS_PATH=$ESHOST_ESVU_PATH/sm;
ESHOST_V8_PATH=$ESHOST_ESVU_PATH/v8;
ESHOST_XS_PATH=$ESHOST_ESVU_PATH/xs;
ESHOST_NODE_PATH=`which node`;

echo ESHOST_ESVU_PATH=${ESHOST_ESVU_PATH};
echo ESHOST_CHAKRA_PATH=${ESHOST_CHAKRA_PATH};
echo ESHOST_ENGINE262_PATH=${ESHOST_ENGINE262_PATH};
echo ESHOST_JSC_PATH=${ESHOST_JSC_PATH};
echo ESHOST_JS_PATH=${ESHOST_JS_PATH};
echo ESHOST_NODE_PATH=${ESHOST_NODE_PATH};
echo ESHOST_V8_PATH=${ESHOST_V8_PATH};
echo ESHOST_XS_PATH=${ESHOST_XS_PATH};
